-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
-- yes, they're out of order, I was ordering them differently at the start and can't be arsed to go back and fix it
LOCATION_MAPPING = {
    [110000] = {"@Shops/Coal Pits Holy Mountain/Shop Items"},
    [110001] = {"@Shops/Coal Pits Holy Mountain/Shop Items"},
    [110002] = {"@Shops/Coal Pits Holy Mountain/Shop Items"},
    [110003] = {"@Shops/Coal Pits Holy Mountain/Shop Items"},
    [110004] = {"@Shops/Coal Pits Holy Mountain/Shop Items"},
    [110005] = {"@Shops/Coal Pits Holy Mountain/Spell Refresher"},
    [110006] = {"@Shops/Snowy Depths Holy Mountain/Shop Items"},
    [110007] = {"@Shops/Snowy Depths Holy Mountain/Shop Items"},
    [110008] = {"@Shops/Snowy Depths Holy Mountain/Shop Items"},
    [110009] = {"@Shops/Snowy Depths Holy Mountain/Shop Items"},
    [110010] = {"@Shops/Snowy Depths Holy Mountain/Shop Items"},
    [110011] = {"@Shops/Snowy Depths Holy Mountain/Spell Refresher"},
    [110012] = {"@Shops/Hiisi Base Holy Mountain/Shop Items"},
    [110013] = {"@Shops/Hiisi Base Holy Mountain/Shop Items"},
    [110014] = {"@Shops/Hiisi Base Holy Mountain/Shop Items"},
    [110015] = {"@Shops/Hiisi Base Holy Mountain/Shop Items"},
    [110016] = {"@Shops/Hiisi Base Holy Mountain/Shop Items"},
    [110017] = {"@Shops/Hiisi Base Holy Mountain/Spell Refresher"},
    [110018] = {"@Shops/Undeground Jungle Holy Mountain/Shop Items"},
    [110019] = {"@Shops/Undeground Jungle Holy Mountain/Shop Items"},
    [110020] = {"@Shops/Undeground Jungle Holy Mountain/Shop Items"},
    [110021] = {"@Shops/Undeground Jungle Holy Mountain/Shop Items"},
    [110022] = {"@Shops/Undeground Jungle Holy Mountain/Shop Items"},
    [110023] = {"@Shops/Undeground Jungle Holy Mountain/Spell Refresher"},
    [110024] = {"@Shops/The Vault/Holy Mountain Shop Items"},
    [110025] = {"@Shops/The Vault/Holy Mountain Shop Items"},
    [110026] = {"@Shops/The Vault/Holy Mountain Shop Items"},
    [110027] = {"@Shops/The Vault/Holy Mountain Shop Items"},
    [110028] = {"@Shops/The Vault/Holy Mountain Shop Items"},
    [110029] = {"@Shops/The Vault Holy Mountain/Spell Refresher"},
    [110030] = {"@Shops/Temple of the Art Holy Mountain/Shop Items"},
    [110031] = {"@Shops/Temple of the Art Holy Mountain/Shop Items"},
    [110032] = {"@Shops/Temple of the Art Holy Mountain/Shop Items"},
    [110033] = {"@Shops/Temple of the Art Holy Mountain/Shop Items"},
    [110034] = {"@Shops/Temple of the Art Holy Mountain/Shop Items"},
    [110035] = {"@Shops/Temple of the Art Holy Mountain/Spell Refresher"},
    [110036] = {"@Shops/Laboratory/Holy Mountain Shop Items"},
    [110037] = {"@Shops/Laboratory/Holy Mountain Shop Items"},
    [110038] = {"@Shops/Laboratory/Holy Mountain Shop Items"},
    [110039] = {"@Shops/Laboratory/Holy Mountain Shop Items"},
    [110040] = {"@Shops/Laboratory/Holy Mountain Shop Items"},
    [110041] = {"@Shops/Laboratory/Holy Mountain Spell Refresher"},
    [110042] = {"@Shops/Secret Shop/Shop Items"},
    [110043] = {"@Shops/Secret Shop/Shop Items"},
    [110044] = {"@Shops/Secret Shop/Shop Items"},
    [110045] = {"@Shops/Secret Shop/Shop Items"},
    [110658] = {"@Orbs and Bosses/Floating Island Orb"},
    [110649] = {"@Orbs and Bosses/Kolmisilmän Koipi"},
    [110659] = {"@Orbs and Bosses/Pyramid Orb"},
    [110662] = {"@Orbs and Bosses/Sandcave Orb"},
    [110526] = {"@Biome Checks/Overgrown Cavern Chests"},
    [110546] = {"@Biome Checks/Overgrown Cavern/Pedestals"},
    [110651] = {"@Orbs and Bosses/Syväolento"},
    [110660] = {"@Orbs and Bosses/Frozen Vault Orb"},
    [110566] = {"@Biome Checks/Frozen Vault/Chests"},
    [110586] = {"@Biome Checks/Frozen Vault/Pedestals"},
    [110046] = {"@Biome Checks/Mines/Chests"},
    [110066] = {"@Biome Checks/Mines/Pedestals"},
    [110656] = {"@Orbs and Bosses/Ylialkemisti"},
    [110650] = {"@Orbs and Bosses/Sauvojen Tuntija"},
    [110665] = {"@Orbs and Bosses/Abyss Orb"},
    [110661] = {"@Orbs and Bosses/Lava Lake Orb"},
    [110126] = {"@Biome Checks/Coal Pits/Chests"},
    [110146] = {"@Biome Checks/Coal Pits/Pedestals"},
    [110166] = {"@Biome Checks/Fungal Caverns/Chests"},
    [110186] = {"@Biome Checks/Fungal Caverns/Pedestals"},
    [110206] = {"@Biome Checks/Snowy Depths/Chests"},
    [110226] = {"@Biome Checks/Snowy Depths/Pedestals"},
    [110663] = {"@Orbs and Bosses/Magical Temple Orb"},
    [110246] = {"@Biome Checks/Hiisi Base/Chests"},
    [110266] = {"@Biome Checks/Hiisi Base/Pedestals"},
    [110648] = {"@Orbs and Bosses/Suomuhauki"},
    [110286] = {"@Biome Checks/Underground Jungle/Chests"},
    [110306] = {"@Biome Checks/Underground Jungle/Pedestals"},
    [110664] = {"@Orbs and Bosses/Lukki Lair Orb"},
    [110326] = {"@Biome Checks/Lukki Lair/Chests"},
    [110346] = {"@Biome Checks/Lukki Lair/Pedestals"},
    [110366] = {"@Biome Checks/The Vault/Chests"},
    [110386] = {"@Biome Checks/The Vault/Pedestals"},
    [110652] = {"@Orbs and Bosses/Gate Guardian"},
    [110406] = {"@Biome Checks/Temple of the Art/Chests"},
    [110426] = {"@Biome Checks/Temple of the Art/Pedestals"},
    [110606] = {"@Biome Checks/The Tower/Chests"},
    [110626] = {"@Biome Checks/The Tower/Pedestals"},
    [110655] = {"@Orbs and Bosses/Mestarien Mestari"},
    [110668] = {"@Orbs and Bosses/Wizard's Den Orb"},
    [110446] = {"@Biome Checks/Wizard's Den/Chests"},
    [110466] = {"@Biome Checks/Wizard's Den/Pedestals"},
    [110657] = {"@Orbs and Bosses/Kolmisilmän silmä"},
    [110486] = {"@Biome Checks/Power Plant/Chests"},
    [110506] = {"@Biome Checks/Power Plant/Pedestals"},
    [110653] = {"@Orbs and Bosses/Unohdettu"},
    [110667] = {"@Orbs and Bosses/Snow Chasm Orb"},
    [110647] = {"@Orbs and Bosses/Limatoukka"},
    [110646] = {"@Orbs and Bosses/Kolmisilmä"},
    [110654] = {"@Orbs and Bosses/Toveri"},
    [110666] = {"@Orbs and Bosses/The Work (Hell) Orb"},
}

-- so we don't have to repetitively add the chest and pedestal location ids
for k, v in pairs(LOCATION_MAPPING) do
    if string.find(v[1], "@Biome Checks") ~= nil then
        for i = k, k + 19 do
            LOCATION_MAPPING[i] = v
        end
    end
end